# Generated by Django 5.1.4 on 2025-01-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_serial_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('qr_code_identifier', models.CharField(blank=True, max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scanned_assets', models.ManyToManyField(related_name='audit_sessions', to='assets.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.branch'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.category'),
        ),
    ]
