# Generated by Django 5.1.6 on 2025-02-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
