# Generated by Django 5.1.4 on 2025-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auditsession_scannedasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditsession',
            old_name='ended_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='auditsession',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='auditsession',
            old_name='started_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='auditsession',
            name='active',
        ),
        migrations.RemoveField(
            model_name='auditsession',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
